# Generated by Django 6.0.6 on 2026-06-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_hostelleave_approval_date_hostelleave_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelleave',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostelleave',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelleave',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
