# Generated by Django 6.0.6 on 2026-07-14 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_hostelleave_destination_hostelleave_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelleave',
            old_name='leave_date',
            new_name='leave_from',
        ),
        migrations.RenameField(
            model_name='hostelleave',
            old_name='return_date',
            new_name='leave_to',
        ),
        migrations.AddField(
            model_name='hostelleave',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelleave',
            name='entry_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostelleave',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelleave',
            name='exit_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostelleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('entered', 'Entered Hostel'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='QRPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pass_type', models.CharField(choices=[('EXIT', 'Exit'), ('ENTRY', 'Entry')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_passes', to='leave.hostelleave')),
            ],
        ),
    ]
