[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"

[deploy]
startCommand = "gunicorn Hostel_Management_System.wsgi --bind 0.0.0.0:$PORT --log-file -"
