[build]
builder = "nixpacks"
buildCommand = "bash build.sh"

[deploy]
releaseCommand = "python manage.py migrate && python manage.py seed_modules && python manage.py seed_super_admin"
startCommand = "gunicorn Hostel_Management_System.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload --log-file -"
