# Generated by Django 6.0.6 on 2026-07-05 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_floor_hostelblock_room_floor_floor_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('BOY', 'Boys'), ('GIRL', 'Girls'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hostel_building',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['floor_number']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number']},
        ),
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(blank=True, choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D'), ('E', 'Block E'), ('F', 'Block F'), ('NORTH', 'North Wing'), ('SOUTH', 'South Wing'), ('EAST', 'East Wing'), ('WEST', 'West Wing')], max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2, help_text='Number of beds in the room'),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP / Premium'), ('STAFF', 'Staff Quarters'), ('RESERVED', 'Reserved')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, help_text='Optional friendly name', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bed',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='gender',
            field=models.CharField(choices=[('BOY', 'Boys'), ('GIRL', 'Girls'), ('MIXED', 'Mixed')], default='BOY', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'Single (1 Bed)'), ('DOUBLE', 'Double (2 Beds)'), ('TRIPLE', 'Triple (3 Beds)'), ('DORMITORY', 'Dormitory'), ('DELUXE', 'Deluxe'), ('AC', 'AC Room'), ('NON_AC', 'Non-AC Room'), ('CUSTOM', 'Custom')], default='DOUBLE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='room.hostelbuilding'),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='room.hostelbuilding'),
        ),
    ]
