# Generated by Django 6.0.6 on 2026-07-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_hostelbuilding_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'room_number')},
        ),
    ]
