# Generated by Django 6.0.6 on 2026-07-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_room_number_alter_room_unique_together'),
        ('student', '0003_alter_student_status_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
