# Generated by Django 6.0.6 on 2026-07-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_hostel'),
        ('room', '0005_alter_bed_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbuilding',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='authentication.hostel'),
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='authentication.hostel'),
        ),
    ]
