# Generated by Django 6.0.6 on 2026-07-12 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('room', '0006_hostelbuilding_hostel_room_hostel'),
        ('student', '0005_student_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='floor',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Max rooms on this floor'),
        ),
        migrations.AddField(
            model_name='floor',
            name='cleaning_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Needs Cleaning'), ('in_progress', 'Cleaning In Progress')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='maintenance_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='block_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='room.hostelbuilding'),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='hostelbuilding',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='hostelbuilding',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='room.room'),
        ),
        migrations.AlterField(
            model_name='hostelblock',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('block', 'floor_number')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelblock',
            unique_together={('building', 'name')},
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(default=None)),
                ('vacated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='room.bed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_allocations', to='student.student')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
    ]
