# Generated by Django 6.0.6 on 2026-07-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_systemsettings_allowed_ips_and_more'),
        ('room', '0007_bed_status_floor_capacity_floor_cleaning_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategoryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP / Premium'), ('STAFF', 'Staff Quarters'), ('RESERVED', 'Reserved')], max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_category_pricings', to='authentication.hostel')),
            ],
            options={
                'db_table': 'room_category_pricing',
                'unique_together': {('hostel', 'category')},
            },
        ),
        migrations.CreateModel(
            name='RoomTypePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single (1 Bed)'), ('DOUBLE', 'Double (2 Beds)'), ('TRIPLE', 'Triple (3 Beds)'), ('DORMITORY', 'Dormitory'), ('DELUXE', 'Deluxe'), ('AC', 'AC Room'), ('NON_AC', 'Non-AC Room'), ('CUSTOM', 'Custom')], max_length=20)),
                ('base_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_pricings', to='authentication.hostel')),
            ],
            options={
                'db_table': 'room_type_pricing',
                'unique_together': {('hostel', 'room_type')},
            },
        ),
    ]
