# Generated by Django 6.0.6 on 2026-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_roomcategorypricing_roomtypepricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategorypricing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomcategorypricing',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomcategorypricing',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomtypepricing',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
