# Generated by Django 6.0.6 on 2026-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_roomcategorypricing_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbuilding',
            name='code',
            field=models.CharField(blank=True, help_text='Building Code e.g. BH-01', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hostelbuilding',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostelbuilding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
