# Generated by Django 6.0.6 on 2026-07-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0011_remove_bedallocation_bed_and_more'),
        ('student', '0005_student_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Boys', 'Boys Wing / Male'), ('Girls', 'Girls Wing / Female')], default='Boys', max_length=10)),
                ('total_floors', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('block', models.CharField(default='A', max_length=10)),
                ('floor', models.IntegerField(default=1)),
                ('room_type', models.CharField(choices=[('2_BED', '2 BED (Double Sharing)'), ('4_BED', '4 BED (Quad Sharing)'), ('CUSTOM', 'CUSTOM (Specify Capacity)')], default='2_BED', max_length=20)),
                ('category', models.CharField(choices=[('GENERAL', 'General Student'), ('DELUXE', 'Deluxe Premium'), ('STAFF', 'Staff / Warden')], default='GENERAL', max_length=20)),
                ('gender', models.CharField(choices=[('Boys', 'Boys Wing / Male'), ('Girls', 'Girls Wing / Female')], default='Boys', max_length=10)),
                ('capacity', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available / Active'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('is_ac', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.hostelbuilding')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_beds', to='student.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='room.room')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
