# Generated by Django 6.0.6 on 2026-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbuilding',
            name='blocks',
            field=models.CharField(blank=True, default='Block A, Block B', help_text='Comma-separated blocks e.g. Block A, Block B', max_length=200, null=True),
        ),
    ]
