# Generated by Django 6.0.6 on 2026-09-13 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_hostelbuilding_blocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='monthly_rent',
        ),
        migrations.CreateModel(
            name='BuildingFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026–2027', max_length=20)),
                ('fee_type', models.CharField(choices=[('MONTHLY_PER_STUDENT', 'Monthly – Per Student')], default='MONTHLY_PER_STUDENT', max_length=30)),
                ('monthly_fee_per_student', models.DecimalField(decimal_places=2, default=6000.0, max_digits=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='room.hostelbuilding')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'building_fee_structure',
                'ordering': ['-academic_year'],
                'unique_together': {('building', 'academic_year')},
            },
        ),
    ]
