# Generated by Django 6.0.6 on 2026-09-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_remove_room_monthly_rent_buildingfeestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfeestructure',
            name='yearly_fee_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buildingfeestructure',
            name='fee_type',
            field=models.CharField(choices=[('MONTHLY_PER_STUDENT', 'Monthly – Per Student'), ('YEARLY_PER_STUDENT', 'Yearly – Per Student')], default='MONTHLY_PER_STUDENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='buildingfeestructure',
            name='monthly_fee_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
