# Generated by Django 6.0.6 on 2026-07-31 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0013_hostelbuilding_blocks'),
        ('student', '0005_student_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_refundable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(default='Razorpay', max_length=50)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='INITIATED', max_length=30)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Base'), ('VARIABLE', 'Variable / Custom')], default='FIXED', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fees.feecategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_type', models.CharField(default='2_BED', max_length=50)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('applicable_for', models.CharField(choices=[('BOYS', 'Boys Hostel'), ('GIRLS', 'Girls Hostel'), ('STAFF', 'Staff Hostel'), ('GUEST', 'Guest')], default='BOYS', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20)),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly (12 Installments)'), ('QUARTERLY', 'Quarterly (4 Installments)'), ('HALF_YEARLY', 'Half-Yearly (2 Installments)'), ('YEARLY', 'Yearly (1 Installment)'), ('ONE_TIME', 'One Time Payment')], default='MONTHLY', max_length=20)),
                ('due_day', models.IntegerField(default=5, help_text='Day of the month e.g. 5th')),
                ('late_fee_rule', models.CharField(choices=[('NONE', 'No Late Fee'), ('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('DAILY', 'Daily Charge')], default='NONE', max_length=20)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grace_period_days', models.IntegerField(default=5)),
                ('allow_partial', models.BooleanField(default=True)),
                ('max_partial_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('enable_online', models.BooleanField(default=True)),
                ('offline_modes', models.CharField(default='Cash, UPI, Bank Transfer, Cheque, Card', max_length=100)),
                ('include_gst', models.BooleanField(default=False)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('total_base_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_fee_with_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='room.hostelbuilding')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('building', 'room_type', 'academic_year', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FeeFineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fine_type', models.CharField(choices=[('LATE_PAYMENT', 'Late Payment Fine'), ('LOST_KEY', 'Lost Key Fine'), ('DAMAGE', 'Room Damage Fine'), ('ROOM_CLEANING', 'Room Cleaning Fine'), ('MESS', 'Mess Fine'), ('CUSTOM', 'Custom Fine')], default='LATE_PAYMENT', max_length=30)),
                ('calculation_type', models.CharField(choices=[('PER_DAY', 'Per Day Charge'), ('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Balance')], default='FIXED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grace_period_days', models.IntegerField(default=5)),
                ('status', models.BooleanField(default=True)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_rules', to='fees.feestructure')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('SCHOLARSHIP', 'Scholarship'), ('SIBLING', 'Sibling Discount'), ('MERIT', 'Merit Discount'), ('SPECIAL', 'Special Discount'), ('EMPLOYEE_CHILD', 'Employee Child'), ('CUSTOM', 'Custom Discount')], default='SCHOLARSHIP', max_length=30)),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='FIXED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='fees.feestructure')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.IntegerField(default=1)),
                ('is_gst_applicable', models.BooleanField(default=False)),
                ('fee_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feecomponent')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fees.feestructure')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('is_locked', models.BooleanField(default=True, help_text='Immutable after issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='room.bed')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fee_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feecomponent')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=60, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fine_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI Payment'), ('BANK', 'Bank Transfer / NEFT / RTGS'), ('CHEQUE', 'Cheque'), ('CARD', 'Debit / Credit Card')], default='UPI', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('upi_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='SUCCESSFUL', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fees.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='student.student')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=60, unique=True)),
                ('qr_code_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='fees.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='student.student')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='fees.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=60, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Processed'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.invoice')),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.paymenttransaction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.IntegerField(default=1)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fees.invoice')),
            ],
            options={
                'ordering': ['installment_no'],
            },
        ),
        migrations.CreateModel(
            name='StudentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INVOICE', 'Invoice Issued (+)'), ('PAYMENT', 'Payment Received (-)'), ('REFUND', 'Refund Issued (+)'), ('DISCOUNT', 'Discount Adjustment (-)'), ('FINE', 'Fine Charge (+)')], max_length=20)),
                ('reference_no', models.CharField(max_length=60)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='student.student')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
