# Generated by Django 6.0.6 on 2026-07-12 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('org_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('hostel_company', 'Hostel Management Company'), ('residential_campus', 'Residential Campus'), ('pg_company', 'PG Management Company'), ('other', 'Other')], default='university', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Hex color', max_length=7)),
                ('secondary_color', models.CharField(default='#0d6efd', help_text='Hex color', max_length=7)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('subdomain', models.CharField(blank=True, help_text='e.g. "abc" for abc.yourerp.com', max_length=100, null=True, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='e.g. hms.abcuniversity.edu', max_length=255)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('max_hostels', models.PositiveIntegerField(default=1, help_text='0 = unlimited')),
                ('max_students', models.PositiveIntegerField(default=100, help_text='0 = unlimited')),
                ('max_staff', models.PositiveIntegerField(default=10, help_text='0 = unlimited')),
                ('storage_gb', models.PositiveIntegerField(default=5)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_ai_features', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('has_mobile_app', models.BooleanField(default=False)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_biometric_integration', models.BooleanField(default=False)),
                ('has_rfid_support', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_academic_year', models.CharField(default='2025-26', max_length=20)),
                ('academic_years', models.JSONField(blank=True, default=list)),
                ('departments', models.JSONField(blank=True, default=list)),
                ('courses', models.JSONField(blank=True, default=list)),
                ('fee_policy', models.TextField(blank=True)),
                ('attendance_policy', models.TextField(blank=True)),
                ('visitor_policy', models.TextField(blank=True)),
                ('leave_policy', models.TextField(blank=True)),
                ('hostel_rules', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Payment Pending'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organizations.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('billing', 'Billing & Subscription'), ('technical', 'Technical Issue'), ('feature_request', 'Feature Request'), ('account', 'Account Management'), ('other', 'Other')], default='technical', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='organizations.organization')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteLabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='whitelabel_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='whitelabel_favicons/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('accent_color', models.CharField(default='#10b981', max_length=7)),
                ('login_background', models.ImageField(blank=True, null=True, upload_to='whitelabel_bg/')),
                ('login_tagline', models.CharField(blank=True, max_length=255)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('report_header', models.TextField(blank=True)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS injected into <head>')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabel', to='organizations.organization')),
            ],
        ),
    ]
