# Generated by Django 6.0.6 on 2026-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='unique_code',
            field=models.CharField(blank=True, help_text='Unique Organization ID / Code', max_length=50, null=True, unique=True),
        ),
    ]
