"""
Django settings for Hostel_Management_System project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
try:
    import dj_database_url  # type: ignore
    HAS_DJ_DATABASE_URL = True
except ImportError:
    HAS_DJ_DATABASE_URL = False

# Load environment variables from .env file (local dev)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Server reload trigger comment - forced refresh
BASE_DIR = Path(__file__).resolve().parent.parent
from django.contrib import messages

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-1%8h(#9yx%1ywjw^!=8!a!#q)@dw6o!(*!5vyb69k2@dr7k@9m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS configuration for local, Railway, and Vercel environments
ALLOWED_HOSTS = ['*']

# CSRF & HTTPS trust for reverse proxies (Railway & Vercel)
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://*.up.railway.app',
    'https://*.vercel.app',
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'student',
    'room',
    'leave',
    'authentication',
    'student_app',
    'warden',
    'hms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.AutoLogout',
    'authentication.middleware.NoRoleAccessMiddleware',
]

ROOT_URLCONF = 'Hostel_Management_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "template",],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'authentication.context_processors.rbac_context',
                'authentication.context_processors.hostel_context',
                'authentication.context_processors.system_settings_context',
                'authentication.context_processors.leave_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hostel_Management_System.wsgi.application'


DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL and HAS_DJ_DATABASE_URL:
    # Production: PostgreSQL via DATABASE_URL (Vercel Postgres, Neon, Supabase, Render, Railway)
    ssl_req = 'sslmode=disable' not in DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=ssl_req
        )
    }
else:
    # Fallback SQLite: Use /tmp/db.sqlite3 in serverless environment (since /vercel/path0 is read-only)
    IS_VERCEL = 'VERCEL' in os.environ or 'AWS_LAMBDA_FUNCTION_NAME' in os.environ
    if IS_VERCEL:
        DB_PATH = Path('/tmp/db.sqlite3')
    else:
        DB_PATH = BASE_DIR / 'db.sqlite3'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DB_PATH,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serve compressed static files efficiently (Django 5+ STORAGES format)
# Using CompressedStaticFilesStorage (not Manifest) to avoid MissingFileError
# for source map references in third-party CSS like bootstrap.min.css.map
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Added Manually
MESSAGE_TAGS={
    messages.ERROR : 'danger'
}


SESSION_COOKIE_AGE = 900  # 15 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Only enforce secure cookies over HTTPS when configured or explicitly enabled
if not DEBUG and os.getenv('ENFORCE_SECURE_COOKIES', 'False').lower() == 'true':
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


LOGIN_URL = '/authentication/login/'  # Update this to the correct path for your login page

# Media files (User uploaded content)
import os
import tempfile

MEDIA_URL = '/media/'
if os.environ.get('VERCEL') or not os.access(str(BASE_DIR), os.W_OK):
    MEDIA_ROOT = os.path.join(tempfile.gettempdir(), 'media')
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Standard Django console logging configurations for production environments
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Forced reload to register newly added module catalog routes.


