# Generated by Django 6.0.6 on 2026-06-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_wardenprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'User Created'), ('edit', 'User Edited'), ('delete', 'User Deleted'), ('activate', 'User Activated'), ('deactivate', 'User Deactivated'), ('lock', 'User Locked'), ('unlock', 'User Unlocked'), ('role_change', 'Role Changed'), ('password_reset', 'Password Reset'), ('export', 'Data Exported'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('gate_pass', 'Gate Pass Action')], max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
