# Generated by Django 6.0.6 on 2026-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_auditlog_action_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class e.g. bi-people', max_length=60),
        ),
        migrations.AddField(
            model_name='module',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Label shown in sidebar menu', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sidebar display order (lower = higher)'),
        ),
        migrations.AddField(
            model_name='module',
            name='parent_code',
            field=models.SlugField(blank=True, help_text='Parent module code for sub-menus', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, help_text='Django URL name for the module index page', max_length=100),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_import',
            field=models.BooleanField(default=False),
        ),
    ]
