# Generated by Django 6.0.6 on 2026-07-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Noble Hostel', max_length=100)),
                ('organization_name', models.CharField(default='Noble Education Group', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='system_favicons/')),
                ('theme_color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('dark_mode_default', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('date_format', models.CharField(default='Y-m-d', max_length=50)),
                ('time_format', models.CharField(default='H:i:s', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('system_version', models.CharField(default='1.0.0', max_length=20)),
                ('license_key', models.TextField(blank=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Global System Settings',
                'verbose_name_plural': 'Global System Settings',
            },
        ),
    ]
