# Generated by Django 6.0.6 on 2026-07-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='code',
            field=models.CharField(default='H01', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_images/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Mixed', 'Mixed')], default='Mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_academic_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_attendance_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_fee_structure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_leave_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_staff_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='separate_visitor_policy',
            field=models.BooleanField(default=False),
        ),
    ]
