# Generated by Django 6.0.6 on 2026-07-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_hostel_capacity_hostel_code_hostel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='authentication.hostel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hostel',
            field=models.ForeignKey(blank=True, help_text='Hostel scope for non-super-admin users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='authentication.hostel'),
        ),
    ]
