# Generated by Django 6.0.6 on 2026-07-14 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auditlog_hostel_auditlog_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Unique permission code e.g. btn_create_room', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human readable name e.g. New Room Button', max_length=150)),
                ('category', models.CharField(choices=[('page', 'Page / View'), ('button', 'Button / CTA'), ('item', 'Minor UI Item / Section'), ('api', 'API Endpoint / Action')], default='button', max_length=20)),
                ('description', models.TextField(blank=True, help_text='What this permission controls')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='authentication.module')),
            ],
        ),
        migrations.CreateModel(
            name='RoleElementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.permissionelement')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_permissions', to='authentication.role')),
            ],
            options={
                'unique_together': {('role', 'element')},
            },
        ),
    ]
