# Generated by Django 6.0.6 on 2026-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_permissionelement_roleelementpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Allowed IP ranges/CSV list (blank to disable check)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_frequency',
            field=models.CharField(default='daily', help_text='Frequency of database backups', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_audit_logs',
            field=models.BooleanField(default=True, help_text='Toggle logging system events'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='login_attempt_limit',
            field=models.IntegerField(default=5, help_text='Max login attempts before lockout'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_expiry_days',
            field=models.IntegerField(default=90, help_text='Force password reset after X days (0 to disable)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='session_timeout',
            field=models.IntegerField(default=1800, help_text='Session timeout in seconds'),
        ),
    ]
