# Generated by Django 6.0.6 on 2026-07-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_systemsettings_allowed_ips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardenprofile',
            name='assigned_blocks',
        ),
    ]
