# Generated by Django 6.0.6 on 2026-09-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_wardenprofile_assigned_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_data',
            field=models.TextField(blank=True, help_text='Base64 Data URI for persistent serverless photo storage', null=True),
        ),
    ]
