# Generated by Django 6.0.6 on 2026-06-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('phonepe', 'PhonePe')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='fee_name',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('rent', 'Hostel Rent'), ('deposit', 'Security Deposit'), ('electricity', 'Electricity Charges'), ('mess', 'Mess Charges'), ('maintenance', 'Maintenance Charges'), ('other', 'Other Charges')], default='other', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
