# Generated by Django 6.0.6 on 2026-06-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0002_gatewayconfig_remove_feestructure_fee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
