# Generated by Django 6.0.6 on 2026-06-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0003_gatewayconfig_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayconfig',
            name='name',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('phonepe', 'PhonePe'), ('demo', 'Demo Gateway (Simulation)')], max_length=20, unique=True),
        ),
    ]
