# Generated by Django 6.0.6 on 2026-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0004_alter_gatewayconfig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part1_due_date', models.DateField(blank=True, null=True, verbose_name='Part 1 Due Date')),
                ('part1_late_fee_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part 1 Late Fee per Day')),
                ('part2_due_date', models.DateField(blank=True, null=True, verbose_name='Part 2 Due Date')),
                ('part2_late_fee_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part 2 Late Fee per Day')),
            ],
            options={
                'verbose_name': 'Installment Configuration',
                'verbose_name_plural': 'Installment Configurations',
            },
        ),
    ]
