# Generated by Django 6.0.6 on 2026-07-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_hostel'),
        ('paybill', '0005_installmentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='authentication.hostel'),
        ),
        migrations.AddField(
            model_name='installmentconfig',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_configs', to='authentication.hostel'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.hostel'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('rent', 'Hostel Rent'), ('deposit', 'Security Deposit'), ('electricity', 'Electricity Charges'), ('mess', 'Mess Charges'), ('maintenance', 'Maintenance Charges'), ('other', 'Other Charges')], default='other', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('hostel', 'fee_type')},
        ),
    ]
