# Generated by Django 5.2 on 2026-03-28 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('course', models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('BA', 'Bachelor of Arts'), ('MA', 'Master of Arts'), ('BSc', 'Bachelor of Science'), ('MSC', 'Master of Science'), ('BCA', 'Bachelor of Computer Applications'), ('MCA', 'Master of Computer Applications'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('PhD', 'Doctor of Philosophy'), ('BCom', 'Bachelor of Commerce'), ('MCom', 'Master of Commerce'), ('BBA LLB', 'Bachelor of Business Administration and Bachelor of Laws'), ('BSc Nursing', 'Bachelor of Science in Nursing'), ('GNM', 'General Nursing and Midwifery'), ('BHMS', 'Bachelor of Homeopathic Medicine and Surgery'), ('BAMS', 'Bachelor of Ayurvedic Medicine and Surgery'), ('CS101', 'Intro to Computer Science'), ('ENG101', 'Intro to Engineering')], max_length=20)),
                ('semester', models.CharField(blank=True, choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th')], max_length=2)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry'), ('California', 'California'), ('Texas', 'Texas'), ('New York', 'New York')], max_length=50)),
                ('city', models.CharField(blank=True, choices=[('Hyderabad', 'Hyderabad'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Rajkot', 'Rajkot'), ('Bhavnagar', 'Bhavnagar'), ('Junagadh', 'Junagadh'), ('Jamnagar', 'Jamnagar'), ('Gandhinagar', 'Gandhinagar'), ('Navsari', 'Navsari'), ('Anand', 'Anand'), ('Bhuj', 'Bhuj'), ('Valsad', 'Valsad'), ('Bharuch', 'Bharuch'), ('Palanpur', 'Palanpur'), ('Porbandar', 'Porbandar'), ('Nadiad', 'Nadiad'), ('Mehsana', 'Mehsana'), ('Surendranagar', 'Surendranagar'), ('Virpur', 'Virpur'), ('Vapi', 'Vapi'), ('Los Angeles', 'Los Angeles'), ('New York City', 'New York City')], max_length=50)),
                ('roll', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
