# Generated by Django 6.0.6 on 2026-06-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='address_line_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('BIO', 'Biotechnology'), ('AE', 'Aerospace Engineering'), ('IT', 'Information Technology'), ('EE', 'Electrical Engineering'), ('ARCH', 'Architecture'), ('BBA', 'Business Administration'), ('MBA', 'Master of Business Administration'), ('BSC', 'Bachelor of Science'), ('MSC', 'Master of Science'), ('PHYS', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematics'), ('BIO', 'Biology'), ('ENV', 'Environmental Science'), ('LAW', 'Law'), ('MED', 'Medicine'), ('PHARMA', 'Pharmacy'), ('DENT', 'Dentistry'), ('NURS', 'Nursing'), ('PSY', 'Psychology'), ('SOC', 'Sociology'), ('ECON', 'Economics'), ('ENG', 'English Literature'), ('HIST', 'History'), ('GEO', 'Geography'), ('POLSCI', 'Political Science'), ('EDU', 'Education'), ('ART', 'Fine Arts'), ('MUS', 'Music'), ('DANCE', 'Dance'), ('THEA', 'Theatre Arts'), ('PHIL', 'Philosophy'), ('LING', 'Linguistics'), ('STAT', 'Statistics'), ('ANTH', 'Anthropology'), ('JMC', 'Journalism and Mass Communication'), ('FASH', 'Fashion Design'), ('TOUR', 'Tourism Management'), ('HM', 'Hotel Management'), ('AGRI', 'Agriculture'), ('VET', 'Veterinary Science'), ('FORE', 'Forestry'), ('HORT', 'Horticulture'), ('FISH', 'Fisheries Science'), ('ANIM', 'Animal Husbandry'), ('RURDEV', 'Rural Development'), ('CS', 'Computer Science'), ('ENG', 'Engineering')], max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C'), ('D', 'Division D')], max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_alt_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Other', 'Other')], default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('BA', 'Bachelor of Arts'), ('MA', 'Master of Arts'), ('BSc', 'Bachelor of Science'), ('MSC', 'Master of Science'), ('BCA', 'Bachelor of Computer Applications'), ('MCA', 'Master of Computer Applications'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('PhD', 'Doctor of Philosophy'), ('BCom', 'Bachelor of Commerce'), ('MCom', 'Master of Commerce'), ('BBA LLB', 'Bachelor of Business Administration and Bachelor of Laws'), ('BSc Nursing', 'Bachelor of Science in Nursing'), ('GNM', 'General Nursing and Midwifery'), ('BHMS', 'Bachelor of Homeopathic Medicine and Surgery'), ('BAMS', 'Bachelor of Ayurvedic Medicine and Surgery'), ('CS101', 'Intro to Computer Science'), ('ENG101', 'Intro to Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
