# Generated by Django 6.0.6 on 2026-07-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_hostel'),
        ('student', '0003_alter_student_status_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='authentication.hostel'),
        ),
    ]
