# Generated by Django 6.0.6 on 2026-07-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_hostel'),
    ]

    operations = [
    ]
