# Generated by Django 6.0.6 on 2026-09-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_photo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026', max_length=20)),
                ('installment_name', models.CharField(help_text='e.g. Installment 1 / Semester 1 Fee', max_length=100)),
                ('due_date', models.DateField()),
                ('percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage of total fee due', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fee_installment',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='FeePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Standard Late Payment Fine', max_length=100)),
                ('penalty_type', models.CharField(choices=[('FIXED', 'Fixed One-Time Fee (₹)'), ('PER_DAY', 'Daily Recurring Late Fee (₹/day)'), ('PERCENTAGE', 'Percentage of Due Amount (%)')], default='PER_DAY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('grace_period_days', models.IntegerField(default=5, help_text='Days after due date before penalty starts applying')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fee_penalty',
                'ordering': ['-created_at'],
            },
        ),
    ]
