# Generated by Django 6.0.6 on 2026-07-04 02:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_alter_student_status_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('assets', 'Assets/Appliances'), ('stock', 'Stock/Ration'), ('consumables', 'Consumables/Cleaning')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('available_quantity', models.IntegerField(default=1)),
                ('vendor_name', models.CharField(blank=True, max_length=150)),
                ('vendor_contact', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('maintenance', 'Under Maintenance'), ('oos', 'Out of Stock')], default='good', max_length=30)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('purchase_order_no', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('gate_no', models.CharField(default='Main Gate 1', max_length=50)),
                ('shift', models.CharField(default='morning', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('theft', 'Theft Alert'), ('trespassing', 'Unauthorized Entry'), ('damage', 'Property Damage'), ('disorder', 'Disorderly Conduct'), ('medical', 'Medical Emergency'), ('fire', 'Fire Alarm'), ('other', 'Other Incident')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High/Critical')], default='low', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.securityguard')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(choices=[('warden', 'Hostel Warden'), ('cleaner', 'Cleaning Staff'), ('chef', 'Kitchen Chef'), ('helpers', 'Kitchen Helper'), ('guard', 'Security Guard'), ('maintenance', 'Maintenance Technician'), ('admin', 'Admin Coordinator')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift (6 AM - 2 PM)'), ('evening', 'Evening Shift (2 PM - 10 PM)'), ('night', 'Night Shift (10 PM - 6 AM)')], default='morning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('performance', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=30)),
                ('doj', models.DateField(default=django.utils.timezone.now)),
                ('documents', models.CharField(blank=True, help_text='List of submitted docs, e.g. Aadhar, Police verification', max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('room', 'Room Maintenance'), ('mess', 'Mess & Food'), ('electricity', 'Electricity & Power'), ('internet', 'Internet & Wi-Fi'), ('cleaning', 'Cleaning & Hygiene'), ('other', 'Other Issues')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Ticket'), ('assigned', 'Ticket Assigned'), ('in_progress', 'Resolution in Progress'), ('resolved', 'Resolved')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback from the student after resolution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='student.student')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='hms.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('relation', models.CharField(help_text='Relation to the student', max_length=50)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('purpose', models.CharField(max_length=255)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved Entry'), ('denied', 'Entry Denied'), ('completed', 'Checked Out')], default='pending', max_length=20)),
                ('pass_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='student.student')),
            ],
        ),
    ]
