# Generated by Django 6.0.6 on 2026-07-05 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
        ('room', '0004_alter_room_room_number_alter_room_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_title', models.CharField(help_text='e.g. Floor Supervisor, Guard, Kitchen Help', max_length=100)),
                ('specific_location', models.CharField(blank=True, help_text='e.g. Main Gate 1, Kitchen, Mess hall', max_length=150)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Specific instructions or notes')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_duties', to='room.hostelblock')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_duties', to='room.hostelbuilding')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_duties', to='room.floor')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='hms.staffprofile')),
            ],
            options={
                'db_table': 'duty_assignment',
                'ordering': ['-assigned_date', 'staff__name'],
            },
        ),
    ]
