# Generated by Django 6.0.6 on 2026-07-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_hostel'),
        ('hms', '0002_dutyassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guards', to='authentication.hostel'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='authentication.hostel'),
        ),
    ]
