# Generated by Django 6.0.6 on 2026-07-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_duty_dutyassignment_duty_dutypermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='guard',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.RemoveField(
            model_name='securityguard',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='student',
        ),
        migrations.DeleteModel(
            name='IncidentReport',
        ),
        migrations.DeleteModel(
            name='SecurityGuard',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
