# Generated by Django 6.0.6 on 2026-07-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_remove_incidentreport_guard_delete_inventoryitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyassignment',
            name='block',
        ),
        migrations.RemoveField(
            model_name='dutyassignment',
            name='building',
        ),
        migrations.RemoveField(
            model_name='dutyassignment',
            name='floor',
        ),
    ]
